/**
 * Configuration du fichier Docker Compose.
 * @module dockerComposeConfig
 * @version 3
 */

services:
  # Service pour l'application Express
  web:
    image: node:latest  # Choisissez la version de Node.js appropriée
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"  # Port d'écoute de l'application Express
    command: sh -c "npm install -f && npm start -f"

  # Service pour la base de données MySQL
  db:
    image: mysql:latest  # Choisissez la version de MySQL appropriée
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: NOTIMAIL
      
    ports:
      - "3306:3306"  # Port d'écoute de MySQL
