POST http://localhost:3000/user
Content-Type: application/json
 {
  "firm_name": "IMTS",
  "phone_number": "08-06-06-06-06",
  "email": "imts@example.com"
}

###
GET http://localhost:3000/user
Content-Type: application/js

###
GET http://localhost:3000/user/McDonald
Content-Type: application/js